Popup window
Bornittah/portifolio pull request #12
Opened 2022-05-20 12:11 UTC by Bornittah

**Interactions**
- Show the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.

**Popup window details**
- Create a JavaScript array of objects to store all of the information for all projects.
- Update the projects section on the main page dynamically with the information stored in the JavaScript object.
- Implement the popup window.

2022-05-20 17:08 UTC, youmari requested changes
Hi @Bornittah , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ No linter error
✔️ Great title and short summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 17:08 UTC, youmari commented on js/app.js
> +
- [ ] please try to remove the unused commented code in order to keep your file clean and professional

2022-05-20 17:08 UTC, youmari commented on js/app.js
>            <li> <a href="#">${tech[3]}</a></li>
- [ ] it would be better if you stick to the Figma design, I see that the tags of the technologies are not like the ones in the Figma design so please try to use the right font and color and background color and should your tags be the same like in the Figma design 
- Figma design 
![image](https://user-images.githubusercontent.com/61790587/169576971-e7ccf707-8c5e-4010-b6fe-03c6b4d9a7be.png)
- Yours 
![image](https://user-images.githubusercontent.com/61790587/169576993-44dc0d4e-d712-47e1-b5d1-c24ce8e0d02c.png)

2022-05-20 17:08 UTC, youmari commented on js/app.js
>          <img src="${obj.featuredImage}" alt="featured-image">
- [ ] your project's image are  not showing up  maybe they do in your machines so please try to fix the `src` link by removing a dot like that `"./assets/images/Img-Plaholder.svg"`

2022-05-20 17:08 UTC, youmari commented on js/app.js
> +                 <img src="./assets/icons/github-white.svg" alt="github">
- [ ] the see live and See Source buttons should be at the bottom of the pop up like in the Figma design please try to fix that 
- Figma 
![image](https://user-images.githubusercontent.com/61790587/169577770-5f036c4e-9776-4f9a-b665-539b1bdf63c6.png)
- Yours 
![image](https://user-images.githubusercontent.com/61790587/169577834-dab3cf0e-c4b2-4be1-a504-8a5eb6fac6dc.png)

2022-05-21 02:58 UTC, roshan-bajgain requested changes
Hi @Bornittah,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 02:58 UTC, roshan-bajgain commented on js/app.js
>          <img src="${obj.featuredImage}" alt="featured-image">
- [ ] As the previous reviewer said your image is still not loaded. Kindly fix it.
- [ ] [Optional] kindly make `X` buttons same as figma design.
### your design
![his](https://user-images.githubusercontent.com/81727988/169632612-269496e8-e3e2-4b68-ac38-9b06260b2859.png)
### Figma design
![figg](https://user-images.githubusercontent.com/81727988/169632621-734bdd8b-daa4-457c-9c5e-297c0b302d5c.png)

2022-05-21 06:55 UTC, aimemalaika approved these changes
Hi @Bornittah, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 06:57 UTC, merged